sudo: false
dist: trusty
language: c

compiler:
  - clang
  - gcc

env:
  - GOAL=stm32
  - GOAL=unix
  - GOAL=src

matrix:
  exclude:
    - compiler: clang
      env: GOAL=stm32
    - compiler: clang
      env: GOAL=src

addons:
  apt:
    packages:
    - build-essential
    - gcc-multilib
    - gcc-arm-none-eabi
    - libnewlib-arm-none-eabi
    - libusb-1.0-0-dev
    - libudev-dev
    - python3
    - python3-pip

install:
    - pip3 install scons
    - pip3 install ed25519 pyblake2
    - pip3 install flake8
    - pip3 install pytest
    - pip3 install ecdsa mnemonic protobuf requests
    - pip3 install git+https://github.com/trezor/python-trezor@master

script:
  - test "$GOAL" != "stm32" || make vendorheader
  - test "$GOAL" != "stm32" || make build_cross
  - test "$GOAL" != "stm32" || make build_boardloader
  - test "$GOAL" != "stm32" || make build_bootloader
  - test "$GOAL" != "stm32" || make build_firmware
  - test "$GOAL" != "stm32" || make sizecheck

  - test "$GOAL" != "unix" || make build_unix_noui
  - test "$GOAL" != "unix" || make test
  - test "$GOAL" != "unix" || make testpy

  - test "$GOAL" != "src" || make style

notifications:
  webhooks:
    urls:
      - http://ci-bot.satoshilabs.com:5000/travis
    on_success: always
    on_failure: always
    on_start: always
