sudo: false
dist: trusty
language: c

addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - build-essential
      - gcc-arm-none-eabi
      - gcc-multilib
      - libnewlib-arm-none-eabi
      - python3.6
      - python3.6-venv
      - python3.6-dev

env:
  global:
    - MAKEFLAGS=-j2
    - PYTHON=python3.6
    - PROTOBUF_VERSION=3.4.0
  matrix:
    - DEBUG_LINK=0
    - DEBUG_LINK=1

matrix:
  include:
      env:
        - EMULATOR=1 HEADLESS=1
        - DEBUG_LINK=1
      script:
        - pipenv run ./script/cibuild && pipenv run script/test

install:
  - curl -LO "https://github.com/google/protobuf/releases/download/v${PROTOBUF_VERSION}/protoc-${PROTOBUF_VERSION}-linux-x86_64.zip"
  - unzip "protoc-${PROTOBUF_VERSION}-linux-x86_64.zip" -d protoc
  - export PATH="$(pwd)/protoc/bin:$PATH"
  - $PYTHON -m ensurepip --user
  - $PYTHON -m pip install --user pipenv
  - pipenv install

script:
  - pipenv run script/cibuild
  - pipenv run make -C bootloader
  - pipenv run make -C demo

notifications:
  webhooks:
    urls:
      - http://ci-bot.satoshilabs.com:5000/travis
    on_success: always
    on_failure: always
    on_start: always
