sudo: required
dist: trusty
language: c

services:
  - docker

addons:
  apt:
    packages:
    - check
    - cmake
    - cmake-data
    - libssl-dev
    - python-pip
    - nodejs

install:
  - pip install --user pytest ecdsa curve25519-donna

script:
  - make
  - ./tests
  - ./test-openssl 1000
  - ITERS=10 py.test
  - mkdir _build && cd _build && cmake .. && make && cd ..
  - cd emscripten && rm trezor-crypto.js && make docker-build && make test-correctness && cd ..

notifications:
  webhooks:
    urls:
      - http://sway.gk2.sk:5000/travis
      - http://163.172.132.178:5000/travis
    on_success: always
    on_failure: always
    on_start: always
