language: python

# Runs jobs on container based infrastructure
sudo: false

# Saves pip downloads/wheels between builds
cache:
  directories:
    - $HOME/.cache/pip

python:
    - "3.5"

install:
    - pip install ed25519 Pillow demjson
    - pip install --no-deps trezor

script:
    - jsonlint defs/*.json
    - cd defs/coins/tools && python build_coins.py

notifications:
  webhooks:
    urls:
      - http://ci-bot.satoshilabs.com:5000/travis
    on_success: always
    on_failure: always
    on_start: always
