[package]
name = "trezor-app-sdk"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib"]

[dependencies]
trezor-structs = { path = "../trezor-structs" }
rkyv = { version = "0.8", default-features = false, features = ["alloc"] }
once_cell = { version = "1.20", default-features = false, features = ["critical-section"] }

[build-dependencies]
quote = "1.0"
syn = "2.0"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
    'cfg(log_level, values("off", "error", "warn", "info", "debug", "trace"))',
] }
