[package]
name = "funnycoin_rust"
version = "0.1.0"
edition = "2024"

[profile.dev]
panic = "abort"
debug = 2      # full DWARF info
strip = "none"

[profile.release]
panic = "abort"
lto = "fat"
codegen-units = 1

[dependencies]
trezor-app-sdk = { path = "../../crates/trezor-app-sdk" }
emballoc = "0.3.0"
prost = { version = "0.14.1", default-features = false, features = ["derive"] }
num_enum = { version = "0.7.5", default-features = false }
ufmt = { version = "0.2.0", default-features = false }
ufmt-utils = "0.2.0"

[build-dependencies]
prost-build = "0.14.1"
