[package]
name = "funnycoin_rust"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[profile.dev]
panic = "abort"
debug = 2      # full DWARF info
strip = "none"

[profile.release]
panic = "abort"
lto = "thin"
codegen-units = 1

[dependencies]
trezor-app-sdk = { path = "../../crates/trezor-app-sdk" }
emballoc = "0.3.0"
critical-section = { version = "1.1", features = ["restore-state-u8"] }
protobuf = { version = "3.7.2", default-features = false, features = ["bytes"] }

[build-dependencies]
protobuf-codegen = "3.7.2"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
    'cfg(log_level, values("off", "error", "warn", "info", "debug", "trace"))',
] }
