[package]
name = "funnycoin_rust"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[[bin]]
name = "trezor-binary"
path = "src/lib.rs"
required-features = ["trezor_binary"]

[features]
trezor_binary = []

[profile.dev]
panic = "abort"
debug = 2      # full DWARF info
strip = "none"

[profile.release]
panic = "abort"
lto = "thin"
codegen-units = 1

[dependencies]
trezor-app-sdk = { path = "../../crates/trezor-app-sdk" }
emballoc = "0.3.0"
prost = { version = "0.14.1", default-features = false, features = ["derive"] }

[build-dependencies]
prost-build = "0.14.1"
