site_name: Trezorlib
repo_url: https://github.com/trezor/trezor-firmware
edit_uri: 'tree/master/python/docs'
site_description: Documentation for trezorlib and trezorctl command
site_author: Trezor/Satoshilabs

theme:
  name: "material"
  highlightjs: true

plugins:
- mkdocstrings:
    handlers:
      python:
        paths: [..]  # so it works from the monorepo root (on readthedocs)
- search

nav:
  - Trezorlib and Trezorctl: index.md
  - Trezorctl examples: EXAMPLES.md
  - Trezorctl commands: OPTIONS.md
  - Transaction Format: transaction-format.md
  - Trezorlib examples: examples_trezorlib.md
  - API Reference:
    - Client: API/client.md
    - Bitcoin: API/btc.md
    - Device: API/device.md
    - Ethereum: API/ethereum.md
    - FIDO: API/fido.md
    - Debuglink: API/debuglink.md

watch:
  - src
