name: Add to GitHub Project

on: [issues, pull_request]

permissions:
  contents: read
  pull-requests: write
  issues: write
  repository-projects: write

jobs:
  gh-automate-projects:
    runs-on: ubuntu-latest
    steps:
      - name: Add new issue to the Backlog ðŸ—‚  project board
        if: github.event_name == 'issues' && github.event.action == 'opened'
        run: |
          gh issue edit $ISSUE --add-project "Backlog ðŸ—‚"
        env:
          ISSUE: ${{github.event.issue.html_url}}
          GITHUB_TOKEN: ${{ secrets.GH_BOT_TOKEN }}

      - name: Add new pull request to the Pull Requests project board
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        run: gh pr edit $PULL_REQUEST --add-project "Pull Requests"
        env:
          PULL_REQUEST: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{ secrets.GH_BOT_TOKEN }}

  add-to-beta-project:
    name: Add new issue to the beta Issues Firmware project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@main
        if: github.event_name == 'issues' && github.event.action == 'opened'
        with:
          project-url: https://github.com/orgs/trezor/projects/60
          github-token: ${{ secrets.GH_BOT_TOKEN }}
